version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=e_shoper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ksy12345
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=e_shoper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ksy12345

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
