apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  namespace: devxhub
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/static
    server: 172.16.188.160

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: devxhub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

